"""Nodes do grafo de campanha."""

from app.graph.nodes.pipeline import (
    create_campaign_node,
    create_crm_company_node,
    create_crm_contact_node,
    create_crm_lead_node,
    find_contacts_node,
    find_emails_node,
    finish_campaign_node,
    normalize_companies_node,
    register_activity_node,
    remove_duplicates_node,
    search_companies_node,
    select_email_template_node,
    select_provider_node,
    send_email_node,
    update_pipeline_node,
    validate_lead_node,
    wait_response_node,
)

__all__ = [
    "create_campaign_node",
    "select_provider_node",
    "search_companies_node",
    "normalize_companies_node",
    "remove_duplicates_node",
    "find_contacts_node",
    "find_emails_node",
    "validate_lead_node",
    "create_crm_company_node",
    "create_crm_contact_node",
    "create_crm_lead_node",
    "select_email_template_node",
    "send_email_node",
    "register_activity_node",
    "wait_response_node",
    "update_pipeline_node",
    "finish_campaign_node",
]
